server:
  port: 8080
spring:
  application:
    name: ncart-pc-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@mahesh.yrlhkv3.mongodb.net/
      database: ncart

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health