server:
  port: 8080
spring:
  application:
    name: ncart-pc-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urotaxidb
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@mahesh.yrlhkv3.mongodb.net/
      database: ncart

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health